In [1]:
import os 
import numpy as np

path = "C:/Users/Raman/OneDrive/Desktop/Signlanguage/sign to text data"
dir_list=os.listdir(path)
print(dir_list)

['A.npy', 'Afternoon.npy', 'B.npy', 'C.npy', 'D.npy', 'E.npy', 'F.npy', 'G.npy', 'H.npy', 'Help.npy', 'I love you .npy', 'I.npy', 'J.npy', 'K.npy', 'L.npy', 'M.npy', 'Me.npy', 'Morning.npy', 'N.npy', 'Night.npy', 'NO SIGN.npy', 'No.npy', 'O.npy', 'Okay.npy', 'P.npy', 'Q.npy', 'R.npy', 'S.npy', 'T.npy', 'U.npy', 'V.npy', 'W.npy', 'X.npy', 'Y.npy', 'Yes.npy']


In [2]:
import os 
import numpy as np

path = "C:/Users/Raman/OneDrive/Desktop/Signlanguage/sign to text data"
dir_list = os.listdir(path)
print(dir_list)
for file in os.listdir(r"C:/Users/Raman/OneDrive/Desktop/Signlanguage/sign to text data"):
    if file.endswith(".npy"):
            print(os.path.join(file))
            

['A.npy', 'Afternoon.npy', 'B.npy', 'C.npy', 'D.npy', 'E.npy', 'F.npy', 'G.npy', 'H.npy', 'Help.npy', 'I love you .npy', 'I.npy', 'J.npy', 'K.npy', 'L.npy', 'M.npy', 'Me.npy', 'Morning.npy', 'N.npy', 'Night.npy', 'NO SIGN.npy', 'No.npy', 'O.npy', 'Okay.npy', 'P.npy', 'Q.npy', 'R.npy', 'S.npy', 'T.npy', 'U.npy', 'V.npy', 'W.npy', 'X.npy', 'Y.npy', 'Yes.npy']
A.npy
Afternoon.npy
B.npy
C.npy
D.npy
E.npy
F.npy
G.npy
H.npy
Help.npy
I love you .npy
I.npy
J.npy
K.npy
L.npy
M.npy
Me.npy
Morning.npy
N.npy
Night.npy
NO SIGN.npy
No.npy
O.npy
Okay.npy
P.npy
Q.npy
R.npy
S.npy
T.npy
U.npy
V.npy
W.npy
X.npy
Y.npy
Yes.npy


In [3]:
import os 
import numpy as np

path = "C:/Users/Raman/OneDrive/Desktop/Signlanguage/sign to text data"
dir_list = os.listdir(path)
print(dir_list)
for file in os.listdir(r"C:/Users/Raman/OneDrive/Desktop/Signlanguage/sign to text data"):
    if file.endswith(".npy"):
            print(os.path.join(file))
            
is_init = False  
size=-1

for i in os.listdir(path):
    if i.split(".")[-1] == "npy":
        if not is_init:
            is_init = True
            X = np.load(os.path.join(path, i))  # Use os.path.join to create the full path
            size = X.shape[0]
            y = np.array([i.split('.')[0]] * size).reshape(-1,1)
        else:
            # Use os.path.join to create the full path
            X = np.concatenate((X, np.load(os.path.join(path, i))))
            y = np.concatenate((y, np.array([i.split('.')[0]] * size).reshape(-1,1)))

print(X.shape)
print(y.shape)

['A.npy', 'Afternoon.npy', 'B.npy', 'C.npy', 'D.npy', 'E.npy', 'F.npy', 'G.npy', 'H.npy', 'Help.npy', 'I love you .npy', 'I.npy', 'J.npy', 'K.npy', 'L.npy', 'M.npy', 'Me.npy', 'Morning.npy', 'N.npy', 'Night.npy', 'NO SIGN.npy', 'No.npy', 'O.npy', 'Okay.npy', 'P.npy', 'Q.npy', 'R.npy', 'S.npy', 'T.npy', 'U.npy', 'V.npy', 'W.npy', 'X.npy', 'Y.npy', 'Yes.npy']
A.npy
Afternoon.npy
B.npy
C.npy
D.npy
E.npy
F.npy
G.npy
H.npy
Help.npy
I love you .npy
I.npy
J.npy
K.npy
L.npy
M.npy
Me.npy
Morning.npy
N.npy
Night.npy
NO SIGN.npy
No.npy
O.npy
Okay.npy
P.npy
Q.npy
R.npy
S.npy
T.npy
U.npy
V.npy
W.npy
X.npy
Y.npy
Yes.npy
(3500, 84)
(3500, 1)


In [38]:
import os 
import numpy as np

path = "C:/Users/Raman/OneDrive/Desktop/Signlanguage"
dir_list = os.listdir(path)
print(dir_list)
for file in os.listdir(r"C:/Users/Raman/OneDrive/Desktop/Signlanguage"):
    if file.endswith(".npy"):
            print(os.path.join(file))

is_init = False 
size=-1

for i in os.listdir(path):
    if i.split(".")[-1] == "npy":
        if not is_init:
            is_init = True
            X = np.load(os.path.join(path, i)) 
            size = X.shape[0]
            y = np.array([i.split('.')[0]] * size).reshape(-1,1)
        else:
            # Use os.path.join to create the full path
            X = np.concatenate((X, np.load(os.path.join(path, i))))
            y = np.concatenate((y, np.array([i.split('.')[0]] * size).reshape(-1,1)))

print(X)
print(y)
print(y.shape)

['desktop.ini', 'Good morning.npy', 'i love you.npy', 'modelss.h5', 'modelss.keras', 'No.npy', 'okay.npy', 'signlanguagedetection (1).py', 'signlanguagedetection.ipynb', 'Untitled14.py', 'yes.npy']
Good morning.npy
i love you.npy
No.npy
okay.npy
yes.npy
[[ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 ...
 [ 0.16292518 -0.01460069  0.07492411 ...  0.          0.
   0.        ]
 [ 0.1585871  -0.00429672  0.06993616 ...  0.          0.
   0.        ]
 [ 0.16255677 -0.00893623  0.07256222 ...  0.          0.
   0.        ]]
[['Good morning']
 ['Good morning']
 ['Good morning']
 ['Good morning']
 ['Good morning']
 ['Good morning']
 ['Good morning']
 ['Good morning']
 ['Good morning']
 ['Good morning']
 ['Good morning']
 ['Good morning']
 ['Good morning']
 ['Good morning']
 ['Good morning']
 ['Good morning']
 ['Good mornin

In [5]:
import os 
import numpy as np

path = "C:/Users/Raman/OneDrive/Desktop/Signlanguage/sign to text data"
dir_list = os.listdir(path)
print(dir_list)
for file in os.listdir(r"C:/Users/Raman/OneDrive/Desktop/Signlanguage/sign to text data"):
    if file.endswith(".npy"):
            print(os.path.join(file))

is_init = False 
size=-1

label=[]
dictionary = {}
c=0

for i in os.listdir(path):
    if i.split(".")[-1] == "npy":
        if not is_init:
            is_init = True
            X = np.load(os.path.join(path, i))  # Use os.path.join to create the full path
            size = X.shape[0]
            y = np.array([i.split('.')[0]] * size).reshape(-1,1)
        else:
            # Use os.path.join to create the full path
            X = np.concatenate((X, np.load(os.path.join(path, i))))
            y = np.concatenate((y, np.array([i.split('.')[0]] * size).reshape(-1,1)))

        label.append(i.split('.')[0])
        dictionary[i.split('.')[0]] = c
        c=c+1
print(dictionary)
print(label)
print(y)


['A.npy', 'Afternoon.npy', 'B.npy', 'C.npy', 'D.npy', 'E.npy', 'F.npy', 'G.npy', 'H.npy', 'Help.npy', 'I love you .npy', 'I.npy', 'J.npy', 'K.npy', 'L.npy', 'M.npy', 'Me.npy', 'Morning.npy', 'N.npy', 'Night.npy', 'NO SIGN.npy', 'No.npy', 'O.npy', 'Okay.npy', 'P.npy', 'Q.npy', 'R.npy', 'S.npy', 'T.npy', 'U.npy', 'V.npy', 'W.npy', 'X.npy', 'Y.npy', 'Yes.npy']
A.npy
Afternoon.npy
B.npy
C.npy
D.npy
E.npy
F.npy
G.npy
H.npy
Help.npy
I love you .npy
I.npy
J.npy
K.npy
L.npy
M.npy
Me.npy
Morning.npy
N.npy
Night.npy
NO SIGN.npy
No.npy
O.npy
Okay.npy
P.npy
Q.npy
R.npy
S.npy
T.npy
U.npy
V.npy
W.npy
X.npy
Y.npy
Yes.npy
{'A': 0, 'Afternoon': 1, 'B': 2, 'C': 3, 'D': 4, 'E': 5, 'F': 6, 'G': 7, 'H': 8, 'Help': 9, 'I love you ': 10, 'I': 11, 'J': 12, 'K': 13, 'L': 14, 'M': 15, 'Me': 16, 'Morning': 17, 'N': 18, 'Night': 19, 'NO SIGN': 20, 'No': 21, 'O': 22, 'Okay': 23, 'P': 24, 'Q': 25, 'R': 26, 'S': 27, 'T': 28, 'U': 29, 'V': 30, 'W': 31, 'X': 32, 'Y': 33, 'Yes': 34}
['A', 'Afternoon', 'B', 'C', 'D', 'E

In [6]:
import os 
import numpy as np

path = "C:/Users/Raman/OneDrive/Desktop/Signlanguage/sign to text data"
dir_list = os.listdir(path)
print(dir_list)

is_init = False 
size = -1

label = []
dictionary = {}
c = 0

for i in os.listdir(path):
    if i.split(".")[-1] == "npy":
        if not is_init:
            is_init = True
            X = np.load(os.path.join(path, i))
            size = X.shape[0]
            y = np.array([i.split('.')[0]] * size).reshape(-1,1)
        else:
            X = np.concatenate((X, np.load(os.path.join(path, i))))
            y = np.concatenate((y, np.array([i.split('.')[0]] * size).reshape(-1,1)))

        label.append(i.split('.')[0])
        dictionary[i.split('.')[0]] = c
        c = c + 1

print(dictionary)
print(label)
print(y)

for i in range(y.shape[0]):
    y[i,0] = dictionary[y[i,0]]
y = np.array(y,dtype="int")
print(y)
        


['A.npy', 'Afternoon.npy', 'B.npy', 'C.npy', 'D.npy', 'E.npy', 'F.npy', 'G.npy', 'H.npy', 'Help.npy', 'I love you .npy', 'I.npy', 'J.npy', 'K.npy', 'L.npy', 'M.npy', 'Me.npy', 'Morning.npy', 'N.npy', 'Night.npy', 'NO SIGN.npy', 'No.npy', 'O.npy', 'Okay.npy', 'P.npy', 'Q.npy', 'R.npy', 'S.npy', 'T.npy', 'U.npy', 'V.npy', 'W.npy', 'X.npy', 'Y.npy', 'Yes.npy']
{'A': 0, 'Afternoon': 1, 'B': 2, 'C': 3, 'D': 4, 'E': 5, 'F': 6, 'G': 7, 'H': 8, 'Help': 9, 'I love you ': 10, 'I': 11, 'J': 12, 'K': 13, 'L': 14, 'M': 15, 'Me': 16, 'Morning': 17, 'N': 18, 'Night': 19, 'NO SIGN': 20, 'No': 21, 'O': 22, 'Okay': 23, 'P': 24, 'Q': 25, 'R': 26, 'S': 27, 'T': 28, 'U': 29, 'V': 30, 'W': 31, 'X': 32, 'Y': 33, 'Yes': 34}
['A', 'Afternoon', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'Help', 'I love you ', 'I', 'J', 'K', 'L', 'M', 'Me', 'Morning', 'N', 'Night', 'NO SIGN', 'No', 'O', 'Okay', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Yes']
[['A']
 ['A']
 ['A']
 ...
 ['Yes']
 ['Yes']
 ['Yes']]
[[ 0]
 [ 0]
 [ 0

In [7]:
import os 
import numpy as np
import cv2 
from tensorflow.keras.utils import to_categorical

path = "C:/Users/Raman/OneDrive/Desktop/Signlanguage/sign to text data"
dir_list = os.listdir(path)
print(dir_list)

is_init = False 
size = -1

label = []
dictionary = {}
c = 0

for i in os.listdir(path):
    if i.split(".")[-1] == "npy":
        if not is_init:
            is_init = True
            X = np.load(os.path.join(path, i))
            size = X.shape[0]
            y = np.array([i.split('.')[0]] * size).reshape(-1,1)
        else:
            X = np.concatenate((X, np.load(os.path.join(path, i))))
            y = np.concatenate((y, np.array([i.split('.')[0]] * size).reshape(-1,1)))

        label.append(i.split('.')[0])
        dictionary[i.split('.')[0]] = c
        c = c + 1

print(dictionary)
print(label)

for i in range(y.shape[0]):
    y[i,0] = dictionary[y[i,0]]
y = np.array(y,dtype="int")
print(y)
print(y.shape)

y=to_categorical(y)
print(y.shape)



['A.npy', 'Afternoon.npy', 'B.npy', 'C.npy', 'D.npy', 'E.npy', 'F.npy', 'G.npy', 'H.npy', 'Help.npy', 'I love you .npy', 'I.npy', 'J.npy', 'K.npy', 'L.npy', 'M.npy', 'Me.npy', 'Morning.npy', 'N.npy', 'Night.npy', 'NO SIGN.npy', 'No.npy', 'O.npy', 'Okay.npy', 'P.npy', 'Q.npy', 'R.npy', 'S.npy', 'T.npy', 'U.npy', 'V.npy', 'W.npy', 'X.npy', 'Y.npy', 'Yes.npy']
{'A': 0, 'Afternoon': 1, 'B': 2, 'C': 3, 'D': 4, 'E': 5, 'F': 6, 'G': 7, 'H': 8, 'Help': 9, 'I love you ': 10, 'I': 11, 'J': 12, 'K': 13, 'L': 14, 'M': 15, 'Me': 16, 'Morning': 17, 'N': 18, 'Night': 19, 'NO SIGN': 20, 'No': 21, 'O': 22, 'Okay': 23, 'P': 24, 'Q': 25, 'R': 26, 'S': 27, 'T': 28, 'U': 29, 'V': 30, 'W': 31, 'X': 32, 'Y': 33, 'Yes': 34}
['A', 'Afternoon', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'Help', 'I love you ', 'I', 'J', 'K', 'L', 'M', 'Me', 'Morning', 'N', 'Night', 'NO SIGN', 'No', 'O', 'Okay', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Yes']
[[ 0]
 [ 0]
 [ 0]
 ...
 [34]
 [34]
 [34]]
(3500, 1)
(3500, 35)


In [9]:
print(y)

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [10]:
import os 
import numpy as np
import cv2 
from tensorflow.keras.utils import to_categorical
from keras.layers import Input, Dense 
from keras.models import Model

path = "C:/Users/Raman/OneDrive/Desktop/Signlanguage/sign to text data"
dir_list = os.listdir(path)
print(dir_list)

is_init = False 
size = -1

label = []
dictionary = {}
c = 0

for i in os.listdir(path):
    if i.split(".")[-1] == "npy":
        if not is_init:
            is_init = True
            X = np.load(os.path.join(path, i))
            size = X.shape[0]
            y = np.array([i.split('.')[0]] * size).reshape(-1,1)
        else:
            X = np.concatenate((X, np.load(os.path.join(path, i))))
            y = np.concatenate((y, np.array([i.split('.')[0]] * size).reshape(-1,1)))

        label.append(i.split('.')[0])
        dictionary[i.split('.')[0]] = c
        c = c + 1


for i in range(y.shape[0]):
    y[i,0] = dictionary[y[i,0]]
y = np.array(y,dtype="int")

y=to_categorical(y)
print(y.shape)

ip = Input(shape=(X.shape[1]))
m = Dense(512, activation="relu")(ip)
m = Dense(256, activation="relu")(m)

op = Dense(y.shape[1], activation="softmax")(m) #for output probabs
model = Model(inputs=ip, outputs=op)
model.compile(optimizer='rmsprop', loss="categorical_crossentropy", metrics=['acc'])

model.fit(X, y, epochs=50)


['A.npy', 'Afternoon.npy', 'B.npy', 'C.npy', 'D.npy', 'E.npy', 'F.npy', 'G.npy', 'H.npy', 'Help.npy', 'I love you .npy', 'I.npy', 'J.npy', 'K.npy', 'L.npy', 'M.npy', 'Me.npy', 'Morning.npy', 'N.npy', 'Night.npy', 'NO SIGN.npy', 'No.npy', 'O.npy', 'Okay.npy', 'P.npy', 'Q.npy', 'R.npy', 'S.npy', 'T.npy', 'U.npy', 'V.npy', 'W.npy', 'X.npy', 'Y.npy', 'Yes.npy']
(3500, 35)


Epoch 1/50


110/110 [==============================] - 2s 5ms/step - loss: 1.9545 - acc: 0.5563
Epoch 2/50
110/110 [==============================] - 1s 5ms/step - loss: 0.3927 - acc: 0.9397
Epoch 3/50
110/110 [==============================] - 0s 4ms/step - loss: 0.1583 - acc: 0.9760
Epoch 4/50
110/110 [==============================] - 1s 6ms/step - loss: 0.1008 - acc: 0.9829
Epoch 5/50
110/110 [==============================] - 1s 6ms/step - loss: 0.0829 - acc: 0.9831
Epoch 6/50
110/110 [==============================] - 1s 5ms/step - loss: 0.0723 - acc: 0.9837
Epoch 7/50
110/110 [==============================] - 0

In [44]:
import os 
import numpy as np
import cv2 
from tensorflow.keras.utils import to_categorical
from keras.layers import Input, Dense 
from keras.models import Model

path = "C:/Users/Raman/OneDrive/Desktop/Signlanguage"
dir_list = os.listdir(path)
print(dir_list)

is_init = False 
size = -1

label = []
dictionary = {}
c = 0

for i in os.listdir(path):
    if i.split(".")[-1] == "npy":
        if not is_init:
            is_init = True
            X = np.load(os.path.join(path, i))
            size = X.shape[0]
            y = np.array([i.split('.')[0]] * size).reshape(-1,1)
        else:
            X = np.concatenate((X, np.load(os.path.join(path, i))))
            y = np.concatenate((y, np.array([i.split('.')[0]] * size).reshape(-1,1)))

        label.append(i.split('.')[0])
        dictionary[i.split('.')[0]] = c
        c = c + 1


for i in range(y.shape[0]):
    y[i,0] = dictionary[y[i,0]]
y = np.array(y,dtype="int")

y=to_categorical(y)

#to shuffle the data
X_new = X.copy()
y_new = y.copy()
counter = 0 

cnt = np.arange(X.shape[0])
np.random.shuffle(cnt)

for i in cnt: 
    X_new[counter] = X[i]
    y_new[counter] = y[i]
    counter = counter + 1
print(y_new)

ip = Input(shape=(X.shape[1]))
m = Dense(512, activation="relu")(ip)
m = Dense(256, activation="relu")(m)

op = Dense(y.shape[1], activation="softmax")(m) #for output probabs
model = Model(inputs=ip, outputs=op)
model.compile(optimizer='rmsprop', loss="categorical_crossentropy", metrics=['acc'])

model.fit(X, y, epochs=50)


['desktop.ini', 'Good morning.npy', 'i love you.npy', 'modelss.h5', 'modelss.keras', 'No.npy', 'okay.npy', 'signlanguagedetection (1).py', 'signlanguagedetection.ipynb', 'Untitled14.py', 'yes.npy']
[[0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 ...
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]]
Epoch 1/50
16/16 [==============================] - 1s 5ms/step - loss: 1.1579 - acc: 0.7140
Epoch 2/50
16/16 [==============================] - 0s 6ms/step - loss: 0.6090 - acc: 0.8080
Epoch 3/50
16/16 [==============================] - 0s 4ms/step - loss: 0.4547 - acc: 0.8400
Epoch 4/50
16/16 [==============================] - 0s 5ms/step - loss: 0.4013 - acc: 0.8580
Epoch 5/50
16/16 [==============================] - 0s 4ms/step - loss: 0.3783 - acc: 0.8560
Epoch 6/50
16/16 [==============================] - 0s 4ms/step - loss: 0.3744 - acc: 0.8560
Epoch 7/50
16/16 [==============================] - 0s 5ms/step - loss: 0.3667 - acc: 0.8600
Epoch 8/50
16/16 [===================

In [11]:
import os 
import numpy as np
import cv2 
from tensorflow.keras.utils import to_categorical
from keras.layers import Input, Dense 
from keras.models import Model

path = "C:/Users/Raman/OneDrive/Desktop/Signlanguage/sign to text data"
dir_list = os.listdir(path)
print(dir_list)

is_init = False 
size = -1

label = []
dictionary = {}
c = 0

for i in os.listdir(path):
    if i.split(".")[-1] == "npy":
        if not is_init:
            is_init = True
            X = np.load(os.path.join(path, i))
            size = X.shape[0]
            y = np.array([i.split('.')[0]] * size).reshape(-1,1)
        else:
            X = np.concatenate((X, np.load(os.path.join(path, i))))
            y = np.concatenate((y, np.array([i.split('.')[0]] * size).reshape(-1,1)))

        label.append(i.split('.')[0])
        dictionary[i.split('.')[0]] = c
        c = c + 1


for i in range(y.shape[0]):
    y[i,0] = dictionary[y[i,0]]
y = np.array(y,dtype="int")

y=to_categorical(y)

#to shuffle the data
X_new = X.copy()
y_new = y.copy()
counter = 0 

cnt = np.arange(X.shape[0])
np.random.shuffle(cnt)

for i in cnt: 
    X_new[counter] = X[i]
    y_new[counter] = y[i]
    counter = counter + 1
print(y_new)

ip = Input(shape=(X.shape[1]))
m = Dense(512, activation="relu")(ip)
m = Dense(256, activation="relu")(m)

op = Dense(y.shape[1], activation="softmax")(m) #for output probabs
model = Model(inputs=ip, outputs=op)
model.compile(optimizer='rmsprop', loss="categorical_crossentropy", metrics=['acc'])

model.fit(X, y, epochs=50)
model.save("modelss.h5")
np.save("labelss.npy", np.array(label))

['A.npy', 'Afternoon.npy', 'B.npy', 'C.npy', 'D.npy', 'E.npy', 'F.npy', 'G.npy', 'H.npy', 'Help.npy', 'I love you .npy', 'I.npy', 'J.npy', 'K.npy', 'L.npy', 'M.npy', 'Me.npy', 'Morning.npy', 'N.npy', 'Night.npy', 'NO SIGN.npy', 'No.npy', 'O.npy', 'Okay.npy', 'P.npy', 'Q.npy', 'R.npy', 'S.npy', 'T.npy', 'U.npy', 'V.npy', 'W.npy', 'X.npy', 'Y.npy', 'Yes.npy']
[[0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Epoch 1/50
110/110 [==============================] - 1s 4ms/step - loss: 2.0312 - acc: 0.5423
Epoch 2/50
110/110 [==============================] - 0s 4ms/step - loss: 0.4186 - acc: 0.9314
Epoch 3/50
110/110 [==============================] - 0s 4ms/step - loss: 0.1582 - acc: 0.9746
Epoch 4/50
110/110 [==============================] - 0s 4ms/step - loss: 0.1010 - acc: 0.9829
Epoch 5/50
110/110 [==============================] - 0s 4ms/step - loss: 0.0817 - acc: 0.9840
Epoch 6/5

C:\ProgramData\Anaconda3\lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [13]:
import os 
import numpy as np
import cv2 
from tensorflow.keras.utils import to_categorical
from keras.layers import Input, Dense 
from keras.models import Model

path = "C:/Users/Raman/OneDrive/Desktop/Signlanguage/sign to text data"
dir_list = os.listdir(path)
print(dir_list)

is_init = False 
size = -1

label = []
dictionary = {}
c = 0

for i in os.listdir(path):
    if i.split(".")[-1] == "npy"and not(i.split(".")[0] == "labels"):
        if not is_init:
            is_init = True
            X = np.load(os.path.join(path, i))
            size = X.shape[0]
            y = np.array([i.split('.')[0]] * size).reshape(-1, 1)
        else:
            X = np.concatenate((X, np.load(os.path.join(path, i))))
            y = np.concatenate((y, np.array([i.split('.')[0]] * size).reshape(-1, 1)))

        label.append(i.split('.')[0])
        dictionary[i.split('.')[0]] = c
        c = c + 1

for i in range(y.shape[0]):
    y[i, 0] = dictionary[y[i, 0]]
y = np.array(y, dtype="int")

y = to_categorical(y)

# Shuffle the data
X_new = X.copy()
y_new = y.copy()
counter = 0

cnt = np.arange(X.shape[0])
np.random.shuffle(cnt)

for i in cnt:
    X_new[counter] = X[i]
    y_new[counter] = y[i]
    counter = counter + 1
print(y)
print(y_new)

ip = Input(shape=(X.shape[1]))
m = Dense(512, activation="relu")(ip)
m = Dense(256, activation="relu")(m)

op = Dense(y.shape[1], activation="softmax")(m)  # For output probabilities
model = Model(inputs=ip, outputs=op)
model.compile(optimizer='rmsprop', loss="categorical_crossentropy", metrics=['acc'])

model.fit(X, y, epochs=50)
model.save("modelss.keras")  # Save as .keras or .h5
np.save("labelss.npy", np.array(label))


['A.npy', 'Afternoon.npy', 'B.npy', 'C.npy', 'D.npy', 'E.npy', 'F.npy', 'G.npy', 'H.npy', 'Help.npy', 'I love you .npy', 'I.npy', 'J.npy', 'K.npy', 'L.npy', 'M.npy', 'Me.npy', 'Morning.npy', 'N.npy', 'Night.npy', 'NO SIGN.npy', 'No.npy', 'O.npy', 'Okay.npy', 'P.npy', 'Q.npy', 'R.npy', 'S.npy', 'T.npy', 'U.npy', 'V.npy', 'W.npy', 'X.npy', 'Y.npy', 'Yes.npy']
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Epoch 1/50
110/110 [==============================] - 1s 5ms/step - loss: 1.9300 - acc: 0.5943
Epoch 2/50
110/110 [==============================] - 1s 5ms/step - loss: 0.3609 - acc: 0.9437
Epoch 3/50
110/110 [==============================] - 1s 5ms/step - loss: 0.1470 - acc: 0.9749
Epoch 4/50
110/110 [=======================